create database Noveno;
DROP DATABASE Noveno;
CREATE DATABASE calibío;
USE Calibio
CREATE TABLE Noveno(
Nombre varchar (50) NOT NULL
Apellido varchar (50) NOT NULL
ID Numeric (10) NPT NULL Primary Key);
Insert Into Noveno VALUES(
"Carlos",
"Valencia", 
2008);
Insert Into Noveno VALUES(
"Martin",
"Chavarro", 
2007);
Insert Into Noveno VALUES(
"Manuel",
"Pereira", 
2007);
Insert Into Noveno VALUES(
"Santiago",
"Gonzales", 
2008);
Insert Into Noveno VALUES(
"Juan",
"Portela", 
2008);
Insert Into Noveno VALUES(
"Mariana",
"Garcia", 
2008);
Insert Into Noveno VALUES(
"Sebastian",
"Rosero", 
2008);
Insert Into Noveno VALUES(
"Juan",
"herrera", 
2006);
Insert Into Noveno VALUES(
"Alejandro",
"Guzman", 
2008);
Insert Into Noveno VALUES(
"Antonia",
"Rodriguez", 
2009);
Insert Into Noveno VALUES(
"Isabella",
"Delgado", 
2007);
Insert Into Noveno VALUES(
"Andres",
"Gomez", 
2007);
Insert Into Noveno VALUES(
"Sarah",
"ordoñez", 
2008);Insert Into Noveno VALUES(
"Silvana",
"Zuluaga", 
2007);
Insert Into Noveno VALUES(
"Jose",
"Jaramillo", 
2008);
Insert Into Noveno VALUES(
"Manuel",
"Figueroa", 
2007);
Insert Into Noveno VALUES(
"mariana",
"Maldroñero", 
2008);
Insert Into Noveno VALUES(
"maria",
"Pabon", 
2008);
Insert Into Noveno VALUES(
"Isabel",
"Monje", 
2008);
Insert Into Noveno VALUES(
"Ximena",
"Borrero", 
2008);
Select*from Noveno(
DATABASE NOVENO Y CALIBIO.txt
Se hizo zoom en el elemento.
Creación de una base de datos
JUAN DIEGO GUTIERREZ TORRES
•
15 sept 2022
50
•
50 puntos
Fecha límite: 15 sept 2022, 12:40

Guia SQL.docx
Word
Comentarios de la clase
